core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from account.views import loginView, registration, profile, logout_view
from django.contrib.auth.views import LogoutView


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('login/', loginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', registration, name='register'),
    path('profile/', profile, name='profile'),
    path('', include('main.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/models.py
from django.db import models
from account.models import UserProfile


class Reason(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)

    def __str__(self):
        return self.title


# for debits reason
class Category(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    icon = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'categories'
    def __str__(self):
        return self.title


# Hisoblar uchun
# Bunda foydalanuvchi bir nechta karta yoki hamyon qo'shishi mumkin
class Wallet(models.Model):
    currencies = (
        ('USD', 'USD'),
        ('RUB', 'RUB'),
        ('UZS', 'UZS'),
    )

    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    icon = models.CharField(max_length=255, null=True, blank=True)
    amount = models.PositiveBigIntegerField(default=0)
    currency = models.CharField(max_length=10, choices=currencies)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title


# model for incomes
# kirimlar uchun model
class Debit(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE) # qaysi user
    wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE) # qaysi wallet dan
    reason = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True) #sababi
    amount = models.PositiveBigIntegerField() #miqdori
    created = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.wallet.title +'-'+ self.reason.title


# for expenses
# chiqimlar uchun
class Credit(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE)
    reason = models.ForeignKey(Reason, on_delete=models.SET_NULL, null=True, blank=True)
    amount = models.PositiveBigIntegerField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.wallet.title +'-'+ self.reason.title

templates/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <!-- Bootstrap JS -->
    <!-- <script src="{% static 'js/bs.js' %}"></script>
    <script src="{% static 'js/bs2.js' %}"></script> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>

    <script src="https://kit.fontawesome.com/b67c8e9692.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;1,500&display=swap" rel="stylesheet">
    
    <!-- Sahifa nomi -->
    <title>{% block title %} {% endblock %}</title>
</head>
<body>

    <style>
      body{
        font-family: 'Poppins', sans-serif;
      }
    </style>


<!-- for post select date -->
<div class="modal fade" id="postModal" tabindex="-1" role="dialog" aria-labelledby="postModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="postModalLabel">{% trans "Qaysi kun uchun hisobot ko'rmoqchisiz?" %}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <!-- Form inside the modal -->
        <form id="postForm" method="post" action="{% url 'selected_date' %}">
          {% csrf_token %}
          <div class="form-group">
            <label for="date">{% trans 'Sanani tanlang' %}</label>
            <input type="date" class="form-control" id="date" name="selected_date" required>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>
  </div>
</div>


    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'index' %}">ExpenseTracker</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            {% get_current_language as CURRENT_LANGUAGE %}
            {% get_available_languages as AVAILABLE_LANGUAGES %}
            {% get_language_info_list for AVAILABLE_LANGUAGES as languages %}
            

            <div class="container d-flex">
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="languageDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {% for language in languages %}
                            {% if language.code == CURRENT_LANGUAGE %}
                                {{ language.name_local }}
                            {% endif %}
                        {% endfor %}
                    </button>
                    <div class="dropdown-menu" aria-labelledby="languageDropdown">
                        {% for language in languages %}
                            <a class="dropdown-item {% if language.code == CURRENT_LANGUAGE %}active{% endif %}" href="/{{ language.code }}/">{{ language.name_local }}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>


            <li class="nav-item active">
              <a class="nav-link" href="{% url 'index' %}">{% trans 'Uy' %}<span class="sr-only">(current)</span></a>
            </li>
            
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'add_categories' %}">{% trans 'Kategoriyalar' %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'wallets' %}">{% trans 'Hamyonlar' %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'profile' %}">Profil</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    <!-- End navbar -->
    {% block content %}
    {% endblock %}
</body>
</html>

templates/inc_and_exp.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}
{% trans 'Kirim va chiqim turlari' %}
{% endblock %}

{% block content %}

{% if messages %}
  <div class="container mt-4">
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
  </div>
{% endif %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2 class="mb-4 mt-5">{% trans 'Kirim turlari' %} <i class="fa-solid fa-arrow-down"></i></h2>
            <table class="table">
                <thead class="black white-text">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">{% trans 'Nomi' %}</th>
                        <th scope="col">
                            <a href="#" class="btn btn-primary rounded-pill" data-toggle="modal" data-target="#modalIncomes"><i class="fa-solid fa-plus"></i></a>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for income in incomes %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ income.title }}</td>
                        <td><a class="text-danger" href="{% url 'delete_category' suffix='income' category_id=income.id %}"><i class="fa-solid fa-trash"></i></a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-md-6">
            <h2 class="mb-4 mt-5">{% trans 'Chiqim turlari' %} <i class="fa-solid fa-arrow-up"></i></h2>
            <table class="table">
                <thead class="grey lighten-2">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">{% trans 'Nomi' %}</th>
                        <th scope="col">
                            <a href="#" class="btn btn-primary rounded-pill" data-toggle="modal" data-target="#modalExpends"><i class="fa-solid fa-plus"></i></a>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for expend in expends %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ expend.title }}</td>
                        <td><a class="text-danger" href="{% url 'delete_category' suffix='expends' category_id=expend.id %}"><i class="fa-solid fa-trash"></i></a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>




<!-- add expends category Modal -->
<div class="modal fade" id="modalExpends" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h4 class="modal-title w-100 font-weight-bold">{% trans "Chiqim turi qo'shish" %}</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body mx-3">
        <form action="" method="post">
          {% csrf_token %}
          <div class="md-form mb-5">
            <div class="form-group">
              <label for="title">{% trans 'Nomi' %}</label>
              <input type="text" name="title" class="form-control" required>
              <input type="hidden" name="which" value="expends">
            </div>
          </div>
          <div class="modal-footer d-flex justify-content-center">
            <button type="submit" class="btn btn-default">{% trans 'Tasdiqlash' %}</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>



<!-- add income category Modal -->
<div class="modal fade" id="modalIncomes" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h4 class="modal-title w-100 font-weight-bold">{% trans "Kirim turi qo'shish" %}</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body mx-3">
        <form action="" method="post">
          {% csrf_token %}
          <div class="md-form mb-5">
            <div class="form-group">
              <label for="title">{% trans 'Nomi' %}</label>
              <input type="text" name="title" class="form-control" required>
              <input type="hidden" name="which" value="income">
            </div>
          </div>
          <div class="modal-footer d-flex justify-content-center">
            <button type="submit" class="btn btn-default">{% trans 'Tasdiqlash' %}</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>



{% endblock %}

templates/monthly_expenses.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}

{% if messages %}
  <div class="container mt-4">
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
  </div>
{% endif %}

<div class="container mt-5">
    <nav class="col text-center mb-5 bg-light sidebar">
        <div class="sidebar-sticky">
          <ul class="nav flex-column">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'index' %}">
                {% trans 'Bugungi hisobotlar' %}
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'weekly_expenses' %}">
                {% trans 'Haftalik hisobotlar' %}
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'monthly_expenses' %}">
                {% trans 'Oylik hisobotlar' %}
              </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#" data-toggle="modal" data-target="#postModal">

                  {% trans 'Tanlangan kun uchun hisobotlar' %}
                </a>
              </li>
          </ul>
        </div>
    </nav>
      <h2 class="text-center text-muted m-5"><i class="fa-solid fa-calendar-days"></i> {{current_month_start}} {% trans 'dan' %} <i class="fa-solid fa-calendar-days"></i>{{current_month_end}} {% trans 'gacha' %} </h2>
    <div class="row">
        <div class="col-md-6">
            <h2 class="mb-4">{% trans 'Haftalik kirimlar' %} <i class="fa-solid fa-arrow-down"></i></h2>
            <table class="table">
                <thead>
                    <tr>
                        <th>{% trans 'Kategoriya' %}</th>
                        <th>{% trans 'Miqdor' %}</th>
                        <th>{% trans 'Valyuta' %}</th>
                        <th>{% trans 'Vaqt' %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% if monthly_incomes %}
                    {% for income in monthly_incomes %}
                    <tr>
                        {% if income.reason.title %}
                        <td>{{ income.reason.title }}</td>
                        {% else %}
                        <td>{% trans 'Yangi hamyon yaratildi' %}</td>
                        {% endif %}
                        <td>{{ income.amount }}</td>
                        <td>{{ income.wallet.currency }}</td>
                        <td>{{ income.created|date:"d-m-Y H:i" }}</td>
                        <td>
                            <button type="button" class="btn btn-danger delete-expense-btn" data-toggle="modal" data-target="#deleteModal" 
                            data-expense-id="{{ income.id }}"
                            data-suffix="income"
                            data-url="monthly_expenses">
                                <i class="fas fa-trash"></i>
                            </button>
                        </td>
                    </tr>
                    {% endfor %}
                    {% endif %}
                </tbody>
            </table>
        </div>

        <div class="col-md-6">
            <h2 class="mb-4">{% trans 'Haftalik chiqimlar' %} <i class="fa-solid fa-arrow-up"></i></h2>
            <table class="table">
                <thead>
                    <tr>
                        <th>{% trans 'Kategoriya' %}</th>
                        <th>{% trans 'Miqdor' %}</th>
                        <th>{% trans 'Valyuta' %}</th>
                        <th>{% trans 'Vaqt' %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% if monthly_expenses %}
                    {% for expense in monthly_expenses %}
                    <tr>
                        {% if expense.reason.title %}
                        <td>{{ expense.reason.title }}</td>
                        {% else %}
                        <td>{% trans 'Yangi hamyon yaratildi' %}</td>
                        {% endif %}
                        <td>{{ expense.amount }}</td>
                        <td>{{ expense.wallet.currency }}</td>
                        <td>{{ expense.created|date:"d-m-Y H:i" }}</td>
                        <td>
                            <button type="button" class="btn btn-danger delete-expense-btn" data-toggle="modal" data-target="#deleteModal" 
                            data-expense-id="{{ expense.id }}" 
                            data-suffix="expense"
                            data-url="monthly_expenses">
                                <i class="fas fa-trash"></i>
                            </button>
                        </td>
                    </tr>
                {% endfor %}
                {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">{% trans 'O\'chirishni tasdiqlash' %}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>{% trans 'O\'chirishni xoxlaysizmi?' %}</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans 'Bekor qilish' %}</button>
                <a id="deleteExpenseLink" class="btn btn-danger" href="">
                    <i class="fas fa-trash"></i> {% trans 'O\'chirish' %}
                </a>
            </div>
        </div>
    </div>
</div>

<script>
    // JavaScript to update the delete link when the modal is shown
    $('#deleteModal').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget);
        var suffix = button.data('suffix');
        var expenseId = button.data('expense-id');
        var url = button.data('url');
        var deleteLink = '/delete/' + suffix + '/' + expenseId + '/' + url + '/';  // Replace with your actual delete URL
        $('#deleteExpenseLink').attr('href', deleteLink);
    });
</script>

{% endblock %}

templates/wallets.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
{% trans 'Hamyonlar' %}
{% endblock %}

{% block content %}

<!-- for display django messages -->
{% if messages %}
  <div class="container mt-4">
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
  </div>
{% endif %}

<div class="container mt-5">
    <h2 class="mb-4">{% trans "Hamyonlar" %}</h2>

    <!-- Display Wallets -->
    <table class="table">
        <thead>
            <tr>
                <th>{% trans "Hamyon nomi" %}</th>
                <th>{% trans "Pul miqdori" %}</th>
                <th>{% trans "Valyuta" %}</th>
                <th>{% trans "Amallar" %}</th>
            </tr>
        </thead>
        <tbody>
            {% if wallets %}
            {% for wallet in wallets %}
                <tr>
                    <td>{{ wallet.title }}</td>
                    <td>{{ wallet.amount }}</td>
                    <td>{{ wallet.get_currency_display }}</td>
                    <td>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#editWalletModal{{ wallet.id }}">
                            <i class="fa-solid fa-pen-to-square"></i>
                        </button>
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteWalletModal{{ wallet.id }}">
                            <i class="fa-solid fa-trash"></i>
                        </button>
                    </td>
                </tr>
                
                <!-- Edit Wallet Modal -->
                <div class="modal fade" id="editWalletModal{{ wallet.id }}" tabindex="-1" role="dialog" aria-labelledby="editWalletModalLabel{{ wallet.id }}" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                        <h5 class="modal-title" id="editWalletModalLabel">{% trans "Hamyonni tahrirlash" %}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        </div>
                        <div class="modal-body">
                            <form method="post" id="editWalletForm" action="{% url 'edit_wallet' %}"> {% csrf_token %}
                                <div class="form-group">
                                    <label for="title">{% trans 'Hamyon nomi' %}</label>
                                    <input type="text" id="title" name="title" value="{{ wallet.title }}" placeholder="{% trans 'masalan, uzcard' %}">
                                </div>
                                <div class="form-group">
                                    <label for="amount">{% trans 'Pul miqdori' %}</label>
                                    <input type="number" id="amount" min="0" name="amount" value="{{ wallet.amount }}" required>
                                </div>
                            
                                <div class="form-group">
                                    <label for="currency">{% trans 'Valyuta' %}</label>
                                    <select name="currency" id="currency">
                                        <option value="{{ wallet.currency }}">{{ wallet.currency }}</option>
                                        {% for currency in currencies %}
                                            {% if wallet.currency != currency %}
                                                <option value="{{ currency }}">{{ currency }}</option>
                                            {% endif %}
                                        {% endfor %}
                                    </select>
                                </div>
                                <input type="hidden" name="wallet_id" value="{{ wallet.id }}">
                                <button type="submit" class="btn btn-primary">{% trans 'Saqlash' %}</button>
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans 'Bekor qilish' %}</button>
                            </form>
                            
                        </div>
                    </div>
                    </div>
                </div>

                <!-- Delete Wallet Modal -->
                <div class="modal fade" id="deleteWalletModal{{ wallet.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteWalletModalLabel{{ wallet.id }}" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                        <h5 class="modal-title" id="deleteWalletModalLabel">{% trans 'Hamyonni o`chirish' %}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        </div>
                        <div class="modal-body">
                            <p>{% trans 'Hamyonni o`chirasizmi?' %} "{{ wallet.title }}"</p>
                            <a href="{% url 'delete_wallet' wallet.id %}" class="btn btn-danger">{% trans 'O`chirish' %}</a>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans 'Bekor qilish' %}</button>
                        </div>
                    </div>
                    </div>
                </div>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="4">{% trans 'Hamyonlar mavjud emas' %}</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
    <!-- Add Wallet Button -->
    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#addWalletModal">
        {% trans 'Hamyon qo\'shish' %}
    </button>

    <!-- Add Wallet Modal -->
    <div class="modal fade" id="addWalletModal" tabindex="-1" role="dialog" aria-labelledby="addWalletModalLabel" aria-hidden="true">
        <!-- Add your add wallet form here -->
        <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="addWalletModalLabel">{% trans "Hamyon qo'shish" %}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <form method="post" id="editWalletForm" action="{% url 'add_wallet' %}"> {% csrf_token %}
                    <div class="form-group">
                        <label for="title">{% trans 'Hamyon nomi' %}</label>
                        <input type="text" id="title" name="title" value="" placeholder="{% trans 'masalan, uzcard, visa' %}" required>
                    </div>
                    <div class="form-group">
                        <label for="amount">{% trans 'Pul miqdori' %}</label>
                        <input type="number" id="amount" min="0" name="amount" value="0" required>
                    </div>

                    <div class="form-group">
                        <label for="currency">{% trans 'Valyutani tanlang' %}</label>
                        <select name="currency" id="" required>
                            {% for currency in currencies %}
                                <option value="{{ currency }}">{{ currency }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">{% trans "Qo'shish" %}</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans 'Bekor qilish' %}</button>
                </form>
              </div>
            </div>
          </div>
    </div>
</div>








{% endblock %}